/* ==============================================================
   APPEARANCE — Light / Dark / System

   The whole palette is two halves: the light values at the top level
   of base.css, theme.css and map.css, and the dark ones inside a
   single `@media (prefers-color-scheme: dark)` block in each. Until
   this file the second half was reachable only by changing the
   device's own setting.

   ⚠️ THE SWITCH REWRITES THE MEDIA QUERY, IT DOES NOT DUPLICATE THE
   PALETTE. The obvious build is a `:root[data-theme="dark"]` copy of
   every dark declaration beside the media block — ~450 lines across
   three files, one of which (theme.css) is GENERATED by
   theme-lab.html and pasted over wholesale. A hand-written copy there
   would be silently destroyed by the next paste, and the app would go
   on looking correct on a dark-mode phone while the toggle quietly
   stopped working. So instead this walks the CSSOM once and sets each
   dark block's own `mediaText` to `all` (force dark) or `not all`
   (force light), and back to the authored condition for System. One
   copy of the palette, and a regenerated theme.css keeps working
   without anybody remembering anything.

   ⚠️ ONLY A TOP-LEVEL BLOCK WHOSE CONDITION IS EXACTLY
   `(prefers-color-scheme: dark|light)` IS TOUCHED. A prefers-color-scheme
   nested inside another query — `@media (min-width:700px) and
   (prefers-color-scheme: dark)`, say — would, forced to `all`, start
   applying at every width. Rewriting the condition can only be safe
   when the condition is the whole of it. All three of the app's dark
   blocks are top level; a nested one added later simply will not
   follow the switch, which is the failure worth having.

   It degrades the way everything optional here does: if no such block
   can be read — a browser that will not hand back cssRules — the
   Appearance row is not drawn at all rather than drawn and dead.

   The choice is PER DEVICE, not per account. It is a fact about the
   screen you are looking at, not about you: the same person on a
   laptop at noon and a phone at midnight wants different answers, and
   syncing it would mean one of the two is always wrong. So it lives
   in localStorage beside the other `bl_*` keys and is deliberately
   NOT cleared by resetAccountState().
   ============================================================== */

const THEME_KEY='bl_theme';
const THEME_MODES=['system','light','dark'];
const THEME_LABELS={system:'System',light:'Light',dark:'Dark'};

/* Matches a whole condition and nothing else — see the second warning
   above. The capture is which half of the palette the block holds. */
const THEME_COND=/^\(\s*prefers-color-scheme\s*:\s*(dark|light)\s*\)$/i;

let themeMode='system';
/* [{rule, dark, orig}] — filled once, lazily. Empty means the switch
   has nothing to act on and the row hides. */
let _themeRules=[];
let _themeScanned=false;
/* The two <meta name="theme-color"> tags and the media each was
   authored with, so System can put them back. */
let _themeMetas=null;

function themeSwitchable(){ return _themeRules.length>0; }
function themeModeLabel(){ return THEME_LABELS[themeMode]||THEME_LABELS.system; }

/* ---- Reading the palette out of the CSSOM ---- */

function scanThemeRules(){
  _themeScanned=true;
  const out=[];
  const sheets=Array.from(document.styleSheets||[]);
  for(const sheet of sheets){
    let rules=null;
    /* Cross-origin (Google Fonts) throws rather than returning null,
       and a sheet that failed to load returns null. Neither is an
       error worth reporting — nothing of ours is in either. */
    try{ rules=sheet.cssRules; }catch(e){ continue; }
    if(!rules) continue;
    for(const rule of Array.from(rules)){
      const isMedia=(window.CSSMediaRule&&rule instanceof CSSMediaRule)||rule.type===4;
      if(!isMedia||!rule.media) continue;
      const cond=(rule.media.mediaText||'').trim();
      const m=THEME_COND.exec(cond);
      if(!m) continue;
      out.push({rule:rule,dark:m[1].toLowerCase()==='dark',orig:cond});
    }
  }
  _themeRules=out;
}

function themeMetas(){
  if(_themeMetas) return _themeMetas;
  _themeMetas=Array.from(document.querySelectorAll('meta[name="theme-color"]'))
    .map(el=>({el:el,orig:el.getAttribute('media')||'',
               dark:/dark/i.test(el.getAttribute('media')||'')}));
  return _themeMetas;
}

/* ---- Applying ---- */

function applyTheme(){
  if(!_themeScanned) scanThemeRules();

  for(const r of _themeRules){
    /* `all` always matches and `not all` never does, so the block is
       switched on or off outright. Back to the authored condition for
       System, which is why `orig` is kept. */
    const want=themeMode==='system'?r.orig
      :((themeMode==='dark')===r.dark?'all':'not all');
    try{ r.rule.media.mediaText=want; }catch(e){}
  }

  /* Native controls and scrollbars read this, not our custom
     properties — a date input inside a sheet is drawn by the UA. */
  document.documentElement.style.colorScheme=
    themeMode==='system'?'':themeMode;

  /* The browser chrome and the PWA status bar evaluate the metas'
     own media, which the rewrite above cannot reach. */
  for(const m of themeMetas()){
    const want=themeMode==='system'?m.orig
      :((themeMode==='dark')===m.dark?'all':'not all');
    m.el.setAttribute('media',want);
  }
}

function setThemeMode(mode){
  if(THEME_MODES.indexOf(mode)<0) return;
  themeMode=mode;
  try{ localStorage.setItem(THEME_KEY,mode); }catch(e){}
  applyTheme();
  renderThemeRow();
}

/* ⚠️ CALLED AT PARSE TIME, from the bottom of this file, and the file
   is FIRST in index.html's script manifest — not from main.js like
   the rest of the boot sequence. A stylesheet blocks the scripts after
   it, so the CSSOM is there to be read; and forcing light on a
   dark-mode phone one tick later would paint the dark palette first
   and correct it, which is a visible flash of the wrong app. */
function initTheme(){
  try{
    const v=localStorage.getItem(THEME_KEY);
    if(THEME_MODES.indexOf(v)>=0) themeMode=v;
  }catch(e){}
  applyTheme();
  /* A sheet that had not finished parsing leaves nothing to find. The
     row would then hide on a switch that does in fact work, so look
     once more when everything is definitely in. */
  if(!_themeRules.length){
    window.addEventListener('load',()=>{
      _themeScanned=false;
      applyTheme();
      renderThemeRow();
    },{once:true});
  }
}

/* ---- The control ---- */

/* Hidden outright when the rewrite found nothing to rewrite — the same
   thing every optional piece of this app does, and better than a row
   that opens a menu whose answers do nothing. */
function renderThemeRow(){
  const row=$('meThemeRow');
  if(!row) return;
  row.style.display=themeSwitchable()?'':'none';
  const val=$('meThemeValue');
  if(val) val.textContent=themeModeLabel();
}

/* A menu rather than a two-state toggle, because System is the third
   answer and the one people need a way back to: a switch can only say
   light or dark, and having chosen one you could never hand the
   decision back to the phone. */
function openThemeMenu(){
  showActionSheet({
    title:'Appearance',
    items:THEME_MODES.map(m=>({
      label:THEME_LABELS[m],
      checked:themeMode===m,
      onSelect:()=>setThemeMode(m),
    })),
  });
}

initTheme();
